### PR TITLE
added spanish translation

### PR DESCRIPTION
**Pull request by carlosgonzz**

### CODE REVIEW

**Comment by carlosgonzz** [comment]
can you change the name of the app to  prevent conflicts. please.

**Comment by sigurg** [comment]
Thanks for the translation.
As for the name change: I'm open to suggestions...
I'm terrible at naming stuff, so I simply named the app "Mooshimeter" to get past the project creation wizard in qtcreator ;)

**Comment by carlosgonzz** [comment]
i also invite  @ExPLIT to help us find a correct name for this wonderful application
at the moment i have some name right now.
Moosher:     MOOSH imet ER.
Volt:             power of energy.
Electron:      is a subatomic particle. 
Watt:            is a unit of power.
eels:             a electric fish name.
Catfish         a electric fish name.
WIP...  i recommend choose or adapt a name to the app based in your idiom if is compatible with ASCII .

**Comment by explit7** [comment]
Hi guys,
Well, i would avoid using the Name Mooshimeter, because 
In German the word Mooshi (Muschi) is the vulgar name of vagina. :)
So the Name Mooshimeter leave a lot of space for interpretation :)

Voltfish is something what i personally like :)

Cheers

ExPLIT


On Friday, 21 September 2018, GNU user wrote:
> i also invite  @ExPLIT to help us find a correct name for this wonderful application
> at the moment i have some name right now.
> Moosher:     MOOSH imet ER.
> Volt:             power of energy.
> Electron:      is a subatomic particle. 
> Watt:            is a unit of power.
> eels:             a electric fish name.
> Catfish         a electric fish name.
> WIP...  i recommend choose or adapt a name to the app based in your idiom if is compatible with ASCII .
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/sigurg/sailfishos-mooshimeter/pull/1#issuecomment-42337430

-- 
Kind regards / 
Mit freundlichen Grüßen

ExPLIT IT Solutions
Pawel Radomychelski

**Comment by carlosgonzz** [comment]
well, is not bad Voltfish, but many like this letter ( III - ltf ) so maybe voltFish or VoltFish?
i like: eels ? let see what the owner think...

**Comment by sigurg** [comment]
Thanks for you suggestions.
I guess I'll go with VoltFish then, by popular demand :)
"eels" while clever, is a bit too cryptic in my opinion... I doubt anyone would guess what kind of app this is, whereas "VoltFish" sound like like an electronics related app.

I will try to finish the rebranding later today...

**Comment by carlosgonzz** [comment]
ok ready to go with "VoltFish".

**Comment by carlosgonzz** [comment]
i would like a new release alpha2 to see how my translation is looking, because some string need more adjust to tranlations i guess. 
thank you.

**Comment by sigurg** [comment]
@ rename & release: done
@ openrepos: I'll be looking into that...

**Comment by carlosgonzz** [comment]
hi sigurg
 can you refresh the translation files? my spanish tranlation
was broken due to severals changes in rename of the app.
also in about-pages the icon of the app is not show anymore.
thanks

**Comment by carlosgonzz** [comment]
@explit i can contribute with 50eu to buy it a device with sailfish OS like(xperia x, fairphone, xperia xa2) to the dev @sigurg.

**Comment by sigurg** [comment]
> can you refresh the translation files? my spanish tranlation
> was broken due to severals changes in rename of the app.

Could you please elaborate on that? I tried switching my phone to spanish and the translations seems to work...

> also in about-pages the icon of the app is not show anymore.

Thanks, I missed that one, because I still had files from the old app on my phone from deploying with qtcreator. Fixed in my local repo, will commit & push later...

> @explit i can contribute with 50eu to buy it a device with sailfish OS like(xperia x, fairphone, xperia xa2) to the dev @sigurg. because intex-aquafish is not supported to use BLE as far i know.

While I appreciate the offer, there's nothing wrong with the aquafish in regards to BLE.
Afaik BLE is not officially supported on any phone, mainly because Jolla can't get their act together and ship a QT5 release with Bluetooth support enabled.
The hardware will supports BLE just fine on my aquafish and the mooshimeter lib I used does not depend on anything but libc sockets and a Linux kernel (as a matter of fact, the same code runs fine on my debian desktop).

Btw, I do plan to get a xa2 as soon as it is officially supported by sailfish.

**Comment by carlosgonzz** [comment]
yes some strings was broken in spanish translation, some still work.
  
i have a aquafish too, i buyed before xperia x get supported. i really like my aquafish. 
can you create a donation link in aboutPage to support this piece-of-gold?

**Comment by sigurg** [comment]
> yes some strings was broken in spanish translation, some still work.

Should be fixed in 0.1.2, I did mess up the way I used the translation macros/functions.
If there are any more problems, please create a new issue.

**Pull request merged**
